# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#

defaults: &defaults
  docker:
      - image: circleci/node:8

version: 2
jobs:
  update:
    <<: *defaults
    steps:
      # Deploy the site to GitHub Pages
      #- add_ssh_keys: *add_ssh_keys
      - checkout:
          path: /tmp/gh-pages
      - deploy:
          name: Update data
          command: |
            git config --global user.email no-reply@teamdigitale.governo.it
            git config --global user.name "Deploy Bot"

            cd /tmp/gh-pages

            if [ `curl -s -w "%{http_code}" --compress -o /tmp/dashboardData.json https://api.daf.teamdigitale.it/anpr/dashboardData.json` = "200" ]; then
              echo "dashboard data updated" && \
              cp /tmp/dashboardData.json ./ && \
              git commit -a -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" || echo "."
            fi

            if [ `curl -s -w "%{http_code}" --compress -o /tmp/previsioni.json https://api.daf.teamdigitale.it/anpr/previsioni` = "200" ]; then
              echo "prevision data updated" && \
              cp /tmp/previsioni.json ./ && \
              git commit -a -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" || echo "."
            fi

            # Install gulp and build
            npm install
            gulp

            # Commit optimized version in docs folder 
            git commit -a -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" || echo "."
            git push origin master


workflows:
  version: 2
  update-dashboard:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update
