# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#

references:
  working_directory: /tmp/gh-pages
  defaults: &defaults
    docker:
      - image: circleci/node:8.1.4-browsers

  npm_permissions: &npm_permissions
    run:
      name: set-user-permissions
      command: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
  npm_install: &npm_install
    run:
      name: install-npm-dependencies
      command: |
        npm install
        npm install gulp-cli -g
        npm install gulp -D
  update_dashboard_data: &update_dashboard_data
    run:
      name: Update dashboard data
      command: |
        git config --global user.email no-reply@teamdigitale.governo.it
        git config --global user.name "Deploy Bot"

        if [ `curl -s -w "%{http_code}" --compress -o /tmp/dashboardData.json https://api.daf.teamdigitale.it/anpr/dashboardData.json` = "200" ]; then
          echo "dashboard data updated" && \
          cp /tmp/dashboardData.json ./ && \
          git commit dashboardData.json  -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" || echo "."
        fi

        if [ `curl -s -w "%{http_code}" --compress -o /tmp/previsioni.json https://api.daf.teamdigitale.it/anpr/previsioni` = "200" ]; then
          echo "prevision data updated" && \
          cp /tmp/previsioni.json ./ && \
          git commit previsioni.json  -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" || echo "."
        fi
        git push origin master
  gulp_build: &gulp_build
    run:
      name: gulp-build
      command: |
        gulp
        git commit docs -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" || echo "."
        git push origin master


version: 2
jobs:
  update:
    <<: *defaults
    steps:
      # Deploy the site to GitHub Pages
      #- add_ssh_keys: *add_ssh_keys
      - checkout
      - << : *npm_permissions
      - << : *npm_install
      - << : *update_dashboard_data
      - << : *gulp_build


workflows:
  version: 2
  commit-workflow:
    jobs:
      - update:
          filters:
            branches:
              only:
                - gulp-ci
  update-dashboard:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update
